a = input('Digite algo: ')
print('O tipo rpimitivo desse valor é',type(a))
print('Tem somente espaços ?', a.isspace())
print('é um numero ?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('esta em maiusculas?',a.isupper())
print('esta em amiusculas ?',a.islower())